version: "3.7"
services:
  webserver:
    env_file: ./.env
    build:
      context: '../'
      dockerfile: './docker/Dockerfile'
      args:
       PHP_VERSION: ${PHP_VERSION}
    links:
      - mailcatcher
    restart: always
    volumes:
      - /var/www/laravel-sessoes:/var/www/html/
      - './php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
      #- './90-xdebug.ini:/usr/local/etc/php/conf.d/90-xdebug.ini'
    container_name: "${PHP_NAME}"
    ports:
        - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: "${MYSQL_NAME}"
  mailcatcher:
    image: tophfr/mailcatcher
    container_name: mailcatcher
    ports:
      - '2080:80'
      - '2025:25'
    restart: always
  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db
volumes:
    redis_volume_data:
    redis_insight_volume_data:

